---

- name: vpc net
  ec2_vpc_net:
    ec2_access_key: '{{ ec2_access_key }}'
    ec2_secret_key: '{{ ec2_secret_key }}'
    name: "{{ vpc_name }}"
    cidr_block: "{{ cidr_block }}"
    region: "{{ region }}"
    tags:
#      this: works
      description:
        - the application tier
#    tenancy: dedicated
  register: vpc
  tags:
    - create_vpc

