oracle_rpm_dependent: [
        { name: 'wget', state: 'present' },
        { name: 'unzip', state: 'present' },
        { name: 'binutils', state: 'present' },
        { name: 'compat-libstdc++-33', state: 'present' },
        { name: 'elfutils-libelf', state: 'present' },
        { name: 'elfutils-libelf-devel', state: 'present' },
        { name: 'expat', state: 'present' },
        { name: 'gcc', state: 'present' },
        { name: 'gcc-c++', state: 'present' },
        { name: 'glibc', state: 'present' },
        { name: 'glibc-common', state: 'present' },
        { name: 'glibc-devel', state: 'present' },
        { name: 'glibc-headers', state: 'present' },
        { name: 'libaio', state: 'present' },
        { name: 'libaio-devel', state: 'present' },
        { name: 'libgcc', state: 'present' },
        { name: 'libstdc++', state: 'present' },
        { name: 'libstdc++-devel', state: 'present' },
        { name: 'make', state: 'present' },
        { name: 'sysstat', state: 'present' },
        { name: 'unixODBC', state: 'present' },
        { name: 'unixODBC-devel', state: 'present' },
]

