

- name: package type to set variables
  set_fact:
    zabbix_version_way_to_judge1: "{{ zabbix_version_way | regex_replace('^zabbix-?.*t', '') }}"
    zabbix_version_way_to_judge2: "{{ zabbix_version_way | regex_replace('^zabbix-?.*p', '') }}"
    zabbix_version_way_to_dir: "{{ zabbix_version_way | regex_replace('.tar(.gz)?', '') }}"

#- name: zabbix_hostmetadata_group py transfer
#  template: src=action_hostmetadata.py.j2 dest=/tmp/action_hostmetadata.py mode=755
#  
#- name: zabbix_hostmetadata_group py run
#  shell: python /tmp/action_hostmetadata.py

- include: "RedHat.yml"


