---

- hosts: all
  user: root
  vars:
    mysql_slave_net_timeout: "60"
    mysql_character_set_server: "utf8"
    mysql_key_buffer_size: "256M"
    mysql_max_allowed_packet: "16M"
    mysql_table_open_cache: "1024"
    mysql_net_buffer_length: "8K"
    mysql_sort_buffer_size: "4M"
    mysql_read_buffer_size: "4M"
    mysql_read_rnd_buffer_size: "16M"
    mysql_myisam_sort_buffer_size: "64"
    mysql_thread_cache_size: "300"
    mysql_query_cache_size: "16M"
    mysql_thread_concurrency: "16"
    mysql_completion_type: "1"
    mysql_wait_timeout: "120"
    mysql_interactive_timeout: "360"
    mysql_bin_log: "/data/log-bin/mysql-bin-3306"
    mysql_bin_log_index: "/data/log-bin/mysql-bin-3306.index"
    mysql_sync_binlog: "1"
    mysql_binlog_format: "mixed"
    mysql_server_id: "1"
    mysql_relay_log: "/data/log-bin/relay-bin-3306"
    mysql_relay_log_index: "/data/log-bin/relay-bin-3306.index"
    mysql_innodb_data_home_dir: "/data/mysql"
    mysql_innodb_log_buffer_size: "8M"
    mysql_innodb_buffer_pool_size: "8192M"
    mysql_innodb_additional_mem_pool_size: "64M"
    mysql_innodb_log_file_size: "256M"
    mysql_innodb_flush_log_at_trx_commit: "1"
    mysql_innodb_lock_wait_timeout: "5"
    mysql_innodb_flush_method: "O_DIRECT"
    mysql_open_files_limit: "65535"
    mysql_max_connections: "5000"
    mysql_innodb_file_per_table: "1"
    mysql_expire_logs_days: "5"
    mysql_log_queries_not_using_indexes: "off"
    mysql_long_query_time: "1"
    mysql_query_size: "16M"
    mysql_query_log: "on"
    mysql_error_log: "/data/log/mysql-error-3306.log"
    mysql_slow_log: "/data/log/mysql-slow-3306.log"
    mysql_relay_log_purge: "0"
    mysql_allowed_packet: "16M"
    mysql_myisamchk_key_buffer_size: "128M"
    mysql_myisamchk_sort_buffer_size: "128M"
    mysql_read_buffer: "2M"
    mysql_write_buffer: "2M"
  roles:
    - mysql
