
- name: create directory
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: directory
  with_items:
    - { path: "{{ tomcat_root_path }}", owner: 'root', group: 'root' }
    - { path: "/root/eos", owner: 'root', group: 'root' }
#    path: "/web"
#    owner: "root"
#    group: "root" 
- name: wget tomcat EOS_Platform on S3
  get_url: 
    dest: "/tmp/"
    url: "https://s3.amazonaws.com/{{ get_bukect_rui }}{{ item.get_package }}"
  with_items: "{{ get_package_uri }}"
  register: package

- set_fact: 
    pack: "{{ package.results }}"


- name: unarchive EOS_Platform_7.2 apache-tomcat
  unarchive:
    src: "/tmp/{{ item.item.get_package }}"
    dest: /{{ tomcat_root_path }}
    mode: 755
    owner: root
    group: root
    remote_src: yes
  with_items: "{{ package.results }}"
#    src: "EOS_Platform_7.2_Enterprise_Edition_Linux.tar" 
#    dest: "/root"
#    mode: 755
#    owner: "root"
#    group: "root"

- name: templates silent_install.properties
  template:
    src: silent_install.properties
    dest: /{{ tomcat_root_path }}/installer/
    mode: 755
    owner: root
    group: root

- name: installer eos
  shell: sh /{{ tomcat_root_path }}/install.sh -silent

