---

- hosts: all
  user: root
  vars:
#auth
    region: "us-east-1"
    ec2_access_key: "AKIAJ4XNWAWSRIFOLUTA"
    ec2_secret_key: "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"
#    ec2_access_key: ""
#    ec2_secret_key: ""

#vpc and subnet resource_tags
    vpc_name: 'test'
    resource_tags_vpc: { Name: 'test' }
    cidr_block: 10.200.0.0/16
    vpc_subnets: [
      { subnets_cidr: '10.200.2.0/24', subnets_az: 'us-east-1a', resource_tags_subnets: { Name: 'app1' } },
#      { subnets_cidr: '10.1.2.0/24', subnets_az: 'us-east-1a', resource_tags_subnets: { Name: 'oracle' } },
#      { subnets_cidr: '10.1.3.0/24', subnets_az: 'us-east-1b', resource_tags_subnets: { Name: 'eos-oracle' } },
    ] 

#safe group
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: icmp
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0

    security_group_name: "vpc-web"

#delete vpc need vpc_id and this vpc is no dependencies
#    delete_vpc_id: vpc-c59d84bc

##get AMI
#    distro: ubuntu
#    release: trusty
#    virt: hvm
#
##instance ec2 and ec2's configure
#    instance_type: t2.micro
#    pair_key_name: Chef
#    security_group_name: [vpc-web]
#    resource_tags_instance_ec2: { Name: 'ansible', type: 'web' }
#    instance_number: 1
#    count_tag: { type: web }
#    vpc_subnet_id: subnet-f4dee9ae 
  roles:
    - init_vpc
